version: '3'
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j:/data
      - neo4jP:/plugins
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_logs_debug_level: DEBUG
  
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
      - ./script.js:/script.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  neo4j:
  neo4jP:
  mongo:
  postgres:

    

